version: '2.0'

services:
  lambda-test:
    image: lambda-test:latest
    container_name: lambda-test
    environment:
      # fill these
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
      AWS_SESSION_TOKEN: ""
    ports:
      - 9000:8080
    # add your gams license file
    volumes:
      - ./gamslice.txt:/var/task/gams33.2_linux_x64_64_sfx/gamslice.txt
