name: gams lambda docker build

on:
  pull_request:
    paths:
      - 'images/gams-lambda-java/**'
  push:
    paths:
      - 'images/gams-lambda-java/**'
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: "./images/gams-lambda-java"
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.working-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set docker tag
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
              echo "TAG=${{ secrets.DOCKER_HUB_USERNAME }}/gams-lambda-java:latest,${{ secrets.DOCKER_HUB_USERNAME }}/gams:$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
          else
              echo "TAG=${{ secrets.DOCKER_HUB_USERNAME }}/gams-lambda-java:test-deploy" >> "$GITHUB_ENV"
          fi

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.working-directory }}
          file: ${{ env.working-directory }}/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ env.TAG }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
